Add AirplaneFile abstraction
airplanedev/js-sdk pull request #164
Opened 2022-10-13 22:17 UTC by geodn

Babel is needed to get fetch-blob to work, and fetch-blob is needed as a browser- and node-compatible implementation of the Blob API.

AirplaneFile is a class that can be used in both views and nodejs tasks/workflows. The plan is to provide convenience factory functions that can construct AirplaneFile from url, from blob, etc.

2022-10-14 12:31 UTC, colinking requested changes

2022-10-14 12:31 UTC, colinking commented on packages/airplane/package.json
> +  "version": "0.2.11",
You have to run `yarn bumpversion` to properly bump the version. That bumps the version in the rest of the workspace.

2022-10-14 12:31 UTC, colinking commented on packages/airplane/index.ts
> +  AirplaneFile,
Let's not include it in the default export. Since the name already includes `Airplane...`, we're already prefixing it such that it can be imported directly.

IOW, we should both default and directly export all methods, but only directly export types and classes. wdyt?

2022-10-14 12:31 UTC, colinking commented on packages/airplane/internal/file/file.ts
> +  constructor(id: string, url: string, name: string, source: Blob) {
Having multiple parameters in a row that have the same type makes the callsites hard to read. Let's use an object instead.

```ts
constructor(source: Blob, metadata: { id: string, url: string, name: string })
```

We also landed on not including the `name` field, right?

2022-10-14 12:31 UTC, colinking commented on packages/airplane/internal/file/file.ts
> +export class AirplaneFile extends Blob {
Add a docstring.

2022-10-14 12:31 UTC, colinking commented on packages/airplane/babel.config.js
> +      "@babel/preset-env",
Add comments explaining why we need this.

2022-10-14 12:31 UTC, colinking commented on packages/airplane/internal/file/file.test.ts
> +import { Blob } from "fetch-blob";
Add a comment describing why we use this `Blob` instead of the native Node.js `Blob`.

2022-10-14 12:31 UTC, colinking commented on packages/airplane/babel.config.js
> +module.exports = {
We also have a `babel.config.js` in the top-level. Should we place this there? https://github.com/airplanedev/js-sdk/blob/main/babel.config.js

2022-10-14 12:31 UTC, colinking commented on packages/airplane/babel.config.js
> +module.exports = {
How is this babel config getting used? We configure Jest to use babel, but don't configure babel anywhere else AFAIK.

2022-10-14 12:35 UTC, colinking commented on packages/airplane/internal/file/file.test.ts
> +  test("works in node", async () => {
Looks like you might be able to add a jsdom test, too, but using this: https://jestjs.io/docs/configuration#testenvironment-string

2022-10-14 12:35 UTC, colinking commented on packages/airplane/internal/file/file.test.ts
> +import { Blob } from "fetch-blob";
Good find on `fetch-blob` :)

2022-10-14 17:46 UTC, geodn commented on packages/airplane/package.json
> +  "version": "0.2.11",
Done.

2022-10-14 17:46 UTC, geodn commented on packages/airplane/index.ts
> +  AirplaneFile,
Done.

2022-10-14 17:51 UTC, geodn commented on packages/airplane/internal/file/file.ts
> +  constructor(id: string, url: string, name: string, source: Blob) {
`name` ends up needed in order to show a card for the uploaded file. My thinking was to not rely on guaranteeing that the last part of url is always the name; seems easier to me if we just set the name based on url if we don't have the name available?

2022-10-14 17:56 UTC, geodn commented on packages/airplane/internal/file/file.test.ts
> +import { Blob } from "fetch-blob";
Added in file.ts.

2022-10-14 18:01 UTC, geodn commented on packages/airplane/babel.config.js
> +module.exports = {
It doesn't work when it's added there - seems like it's using the babel config from the `airplane` directory.

2022-10-14 18:33 UTC, geodn commented on packages/airplane/babel.config.js
> +module.exports = {
It's required to get tests to pass. Honestly I'm not fully sure what's happening, but I think fetch-blob is implemented with a different version of js (ES6?) and there's some compatibility issues that are resolved by babel. Here's the full error when the babel config isn't present:

```
Test suite failed to run
                                                                                                                          
    Jest encountered an unexpected token             
                                                             
    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.                                                                     
                                                             
    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.                                                                                                                  
                                                             
    By default "node_modules" folder is ignored by transformers.                                                          
                                                             
    Here's what you can do:                                                                                               
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.   
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript                   
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.                                                                                                                     
     • If you need a custom transformation specify a "transform" option in your config.                                   
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.                                                                                                          
                                                             
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration            
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation                                                                            
                                                             
    Details:                                              
                                                             
    /Users/georgedu/go/src/github.com/airplanedev/js-sdk/node_modules/fetch-blob/index.js:4
    import './streams.cjs'; // 64 KiB (same size chrome slice theirs blob into Uint8array's)                              
    ^^^^^^                                         
                                                             
    SyntaxError: Cannot use import statement outside a module 
```

2022-10-14 18:34 UTC, geodn commented on packages/airplane/babel.config.js
> +      "@babel/preset-env",
Done.

2022-10-14 18:38 UTC, geodn commented on packages/airplane/internal/file/file.test.ts
> +  test("works in node", async () => {
Very cool! Would we create something like file.jsdom.test.ts?

It does look like it requires a newer version of jest than the one we're using presently (29.1)

2022-10-17 21:47 UTC, colinking approved these changes
Looks great!

2022-10-17 21:47 UTC, colinking commented on packages/airplane/babel.config.js
> +module.exports = {
Good catch. AFAICT, that top-level babel config was not getting used. I pushed up a commit to remove it.

2022-10-17 22:21 UTC, merged