Add request timeouts and check for temporal cancellationSignal
airplanedev/js-sdk pull request #172
Opened 2022-10-26 14:56 UTC by ericliuche

This change adds support for request timeouts to the api client and also checks temporal's context cancellationSignal to allow us to early abort a request if a workflow has been cancelled.

2022-10-26 14:56 UTC, ericliuche commented
Still testing this change, but putting it up in case people have thoughts

2022-10-26 15:00 UTC, ericliuche commented on packages/airplane/internal/api/fetcher.ts
>        throw await HTTPError.newFromResponse(method, response);
should we retry the request if it time's out? the issue here is we can't necessarily tell if the request abort was due to timeout or workflow request cancellation :/

2022-10-26 20:33 UTC, colinking requested changes
Great catch on this!

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +import { AbortSignal } from "abort-controller";
Add `abort-controller` as a dependency.

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +    opts: { enableTracing?: boolean; signal?: AbortSignal; timeoutMs?: number } = {}
nit

```suggestion
    opts: { enableTracing?: boolean; abortSignal?: AbortSignal; timeoutMs?: number } = {}
```

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +    opts: { enableTracing?: boolean; signal?: AbortSignal; timeoutMs?: number } = {}
Maybe define this struct above and re-use it below? That way you can add doc comments.

```typescript
// ...
type RequestOptions = {
  // ...
  enableTracing?: boolean
  // ...
  abortSignal?: AbortSignal
  // ...
  timeoutMs?: number
}
```

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +  async request<Output = unknown>(
Nice refactor.

```suggestion
  protected async request<Output = unknown>(
```

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +      params?: Record<string, unknown>;
```suggestion
      queryParams?: Record<string, unknown>;
```

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
>        throw await HTTPError.newFromResponse(method, response);
Could you just check `opts.signal.aborted` to see if it was a cancellation?

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +    if (!opts.enableTracing) {
😄 

```suggestion
    if (opts.enableTracing) {
```

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +      return await tracer.startActiveSpan(`fetcher.${method.toLowerCase()}`, async (span) => {
Is it more idiomatic to name the span `fetch` and move the method to an attribute? If not sure, backwards-compat is fine with me.

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +          return makeRequest();
Otherwise you leave the `try` clause too early.

```suggestion
          return await makeRequest();
```

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +      setTimeout(() => controller.abort(), opts.timeoutMs);
Make sure to `clearTimeout`, e.g. if the request finishes before the timeout.

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +        opts.signal.removeEventListener("abort", onAbort);
Make sure to `removeEventListener` once the request finishes, if not aborted.

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
>        throw await HTTPError.newFromResponse(method, response);
What does the error look like? We might want to catch the error here and convert it into a pretty error message.

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +      setTimeout(() => controller.abort(), opts.timeoutMs);
What is the default timeout value for `fetch`? Maybe we should we always set one?

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/client.ts
> +        timeoutMs: 30 * 1000,
I don't expect the response to take much time.

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/client.ts
> +      { signal: opts?.signal }
add a timeout

2022-10-26 20:33 UTC, colinking commented on packages/airplane/internal/api/client.ts
> +        timeoutMs: 30 * 1000,
How about a 10s timeout by default, and bump the execute runbook timeout to 30s? (that endpoint is known to be slow).

2022-10-26 20:34 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +      setTimeout(() => controller.abort(), opts.timeoutMs);
Can you add a test case that covers a timeout and another that covers an abort signal? 🙏🏻

2022-10-28 19:54 UTC, ericliuche commented on packages/airplane/internal/api/fetcher.ts
> +      return await tracer.startActiveSpan(`fetcher.${method.toLowerCase()}`, async (span) => {
gonna keep as is for backwards compat for now

2022-10-28 20:12 UTC, ericliuche commented on packages/airplane/internal/api/fetcher.ts
> +      setTimeout(() => controller.abort(), opts.timeoutMs);
default is no timeout, set our default to 10s for now

2022-10-31 14:11 UTC, ericliuche commented on packages/airplane/internal/api/fetcher.ts
>        throw await HTTPError.newFromResponse(method, response);
The error looks like `The user aborted a request.`. Temporal seems to check `https://github.dev/temporalio/sdk-typescript/blob/eb765683e5376fa3c79d035c5e79b053ad02d706/packages/worker/src/activity.ts#L94` for the AbortError and turns it into a CancelledFailure

2022-10-31 14:33 UTC, ericliuche commented on packages/airplane/internal/api/fetcher.ts
>        throw await HTTPError.newFromResponse(method, response);
Event if we don't differentiate the timeout from the cancellation, i think it's fine. In the case that the timeout happened, we'll retry again. In the case that there's been a cancellation, the signal will stay aborted and the request  wont start.

<img width="629" alt="Screen Shot 2022-10-31 at 10 33 17 AM" src="https://user-images.githubusercontent.com/11494140/199033032-13bf9a81-5641-4082-a338-60291a5724c4.png">

2022-10-31 18:45 UTC, ericliuche commented
Ah heck `AbortController` seems to have been introduced in node 15 :( is there a good way around that @colinking ?

2022-10-31 20:40 UTC, colinking commented
@ericliuche you can use a polyfill, e.g. https://www.npmjs.com/package/abort-controller

2022-10-31 21:05 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +          opts.abortSignal.removeEventListener("abort", onAbort);
fwiw you can do `opts.abortSignal?.removeEventListener(...)` instead of having the `if` check

2022-10-31 21:07 UTC, colinking approved these changes
LGTM, only remaining nit is to improve the error message before merging!

2022-10-31 21:26 UTC, ericliuche commented on packages/airplane/internal/api/fetcher.ts
> +              return true;
in the case that a request times out, i think we do still want to retry? like if our API is just being flaky. the issue is we can't differentiate here between `request timed out due to flakiness` and `request aborted due to signal` but i think its fine even to retry the latter since calling `fetch` with an already aborted signal just immediately returns with the Abort error

2022-10-31 21:39 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +              return true;
But won't the controller be aborted in the timeout case, too?

2022-10-31 21:39 UTC, ericliuche commented on packages/airplane/internal/api/fetcher.ts
> +              return true;
yeah, but i thought we would want to retry timeouts?

2022-10-31 21:43 UTC, colinking commented on packages/airplane/internal/api/fetcher.ts
> +              return true;
These retries are happening within the `await fetch()` call. The timeout added in this PR applies across _all retries_, not an individual instance of a retry.

I'm open to retrying on timeout, but I'm just pointing out that it doesn't work as-is.

2022-10-31 21:44 UTC, ericliuche commented on packages/airplane/internal/api/fetcher.ts
> +              return true;
ohhhhhh

2022-11-01 02:00 UTC, ericliuche commented on packages/airplane/internal/api/fetcher.ts
> +        onAbort();
yeah, it sets the `controller` to aborted so the `fetch` will raise the abort error that the temporal sdk expects. Calling `removeEventListener` without a valid identifier is fine, https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

```
Calling removeEventListener() with arguments that do not identify any currently registered [event listener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#the_event_listener_callback) on the EventTarget has no effect.
```

2022-11-01 16:25 UTC, merged