Add prompt tuples
airplanedev/js-sdk pull request #206
Opened 2022-11-21 22:17 UTC by ericliuche

2022-11-22 16:07 UTC, colinking commented on packages/airplane/internal/params/params_output.ts
> +  paramValues: InputToOutputParamValues<TParams>
```suggestion
  paramValues: InputToSerializedParamValues<TParams>
```

2022-11-23 14:45 UTC, ericliuche commented on packages/airplane/internal/params/params_serialized.ts
> +    return paramValue.toISOString();
this was incorrect before. `toISOString(paramValue)` created a format our API doesn't support

2022-11-23 14:45 UTC, ericliuche commented on packages/airplane/internal/params/params_serialized.ts
> +                serializeOptions(param.options as any, slug, optional)
i wasn't able to figure out how to get this type to work :(

2022-11-23 14:46 UTC, ericliuche commented on packages/airplane/internal/params/params_serialized.ts
> +const serializeOptions = <TOption extends InputParamValueByType[keyof InputParamValueByType]>(
before, the option values were represented as the index into the options array, why was this the case @colinking? it created odd artifacts where if you submit a prompt with options in slack, it would render the option values as the index value

2022-11-23 14:48 UTC, ericliuche commented on packages/airplane/internal/params/params_output.ts
> +  const output = {} as Record<keyof TParams, any>;
wasn't able to get this type to work without `any`

2022-11-23 14:49 UTC, ericliuche commented on packages/airplane/internal/prompt/index.test.ts
> +        // @ts-ignore
wasn't able to get this type working

2022-11-23 14:49 UTC, ericliuche commented on packages/airplane/internal/prompt/index.test.ts
> +        // @ts-ignore
wasn't able to get this type working

2022-11-23 14:50 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +const serializeOptions = <TOption extends InputParamValueByType[keyof InputParamValueByType]>(
It was an easy way to get a unique identifier of each element. e.g. if you have a list of objects, do you have to serialize the object to get an identifier?

2022-11-23 14:51 UTC, colinking commented
@ericliuche is this ready for another review? Just re-request from me

2022-11-23 14:56 UTC, ericliuche commented on packages/airplane/internal/params/params_serialized.ts
> +    return paramValue.toISOString();
our parameter definition format doesn't accept ISO strings, trying to define a inline task date param or prompt param with options/defaults surfaces
`Error: Api: 400 - Parameters[1].default: Dates must be formatted as '2006-01-02'`

2022-11-23 14:57 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +    return paramValue.toISOString();
Ah, that's a bug then. Here's the PR: https://github.com/airplanedev/airport/pull/3503/files

2022-11-23 15:17 UTC, ericliuche commented on packages/airplane/internal/prompt/index.ts
> +export const prompt = async <TParams extends PromptInputParams = Record<string, never>>(
i wasn't able to get `airplane.prompt(...)` and `airplane.prompt.text(...)` both to work, i tried something like
```
import { prompt } from "./internal/prompt";
import * as promptFunctions from "./internal/prompt";

prompt.confirm = promptFunctions.confirm;
prompt.text = promptFunctions.text;
prompt.longText = promptFunctions.longText;
prompt.sql = promptFunctions.sql;
prompt.number = promptFunctions.number;
prompt.integer = promptFunctions.integer;
prompt.boolean = promptFunctions.boolean;
prompt.date = promptFunctions.date;
prompt.datetime = promptFunctions.datetime;
prompt.select = promptFunctions.select;
```
but when trying to use `prompt.option.select` i would get 

<img width="876" alt="Screen Shot 2022-11-23 at 10 17 35 AM" src="https://user-images.githubusercontent.com/11494140/203582554-c380a48a-0291-49d1-9e34-30b005ec99de.png">

2022-11-23 15:19 UTC, ericliuche commented on packages/airplane/internal/prompt/index.ts
> +export const prompt = async <TParams extends PromptInputParams = Record<string, never>>(
and for backwards compat im guessing we'd also keep around
```
packages/airplane/prompt.ts

// Supports:
// import { text } from 'airplane/prompt'
export * from "./internal/prompt";

// Supports:
// import prompt from 'airplane/prompt'
export * as default from "./internal/prompt";
```
for now?

2022-11-23 15:21 UTC, ericliuche commented
@colinking ready now!

2022-11-23 17:39 UTC, colinking reviewed
Oof there's a lot here 😄 First pass of comments.

2022-11-23 17:39 UTC, colinking commented on packages/airplane/internal/execute.test.ts
> -          date: "2022-10-31T00:00:00-07:00",
This looks wrong. We purposefully serialize date types in the current user's timezone so that we don't get "off-by-one" bugs where switching to UTC changes the day.

2022-11-23 17:39 UTC, colinking commented on packages/airplane/internal/params/params.ts
> +// TODO: support configvars and uploads
Can you add a Linear? Easier to track.

2022-11-23 17:39 UTC, colinking commented on packages/airplane/internal/params/params_input.ts
> + */
```suggestion
/**
 * PromptInputParams are the subset of InputParams that are available to prompts.
 *
 * Currently config variables and files are not supported by prompts. Once those are supported,
 * we can remove this in favor of using InputParams directly.
 */
```

2022-11-23 17:39 UTC, colinking commented on packages/airplane/internal/params/params_output.test.ts
> +describe("deserializeParamValues", () => {
nice

2022-11-23 17:39 UTC, colinking commented on packages/workflow-runtime/internal/index.ts
> +  prompt: async <TParams extends InputParams = Record<string, never>>(
I find it easier to avoid defaults unless there's a good reason for them (e.g. a type exported to end-users that won't get inferred).

2022-11-23 17:39 UTC, colinking commented on packages/workflow-runtime/internal/index.ts
> +    prompt: PromptConfig
nit: rename to `CreatePromptRequest`. Better conveys this is an API type. I thought it was the user-facing type at first.

2022-11-23 17:39 UTC, colinking commented on packages/airplane/internal/prompt/index.ts
> -  return values[param.slug] as string;
:awyis: I love this

2022-11-23 17:39 UTC, colinking commented on packages/airplane/internal/prompt/index.ts
>  export const datetime = async (
Minor, but would it make sense to rewrite all these methods to just call `.prompt()`? e.g. you wouldn't need to do the conversion to output values.

2022-11-23 17:39 UTC, colinking commented on packages/airplane/internal/prompt/index.ts
> +export const prompt = async <TParams extends PromptInputParams = Record<string, never>>(
Hmm, weird. I'll TAL.

2022-11-23 18:21 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +                serializeOptions(param.options as any, slug, optional)
Hmm, for some reason it's tripping on the union types here:

<img width="1305" alt="CleanShot 2022-11-23 at 12 59 06" src="https://user-images.githubusercontent.com/2907397/203616942-132adfbf-7402-4e4e-959a-58da6e5e9696.png">

And reducing that to just `string | Date`:

<img width="1064" alt="CleanShot 2022-11-23 at 12 59 34" src="https://user-images.githubusercontent.com/2907397/203616985-399bacee-39f7-4096-af69-5b4974be2e30.png">

Not sure the fix, can leave as-is.

2022-11-23 18:21 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +    throw new Error(`The required prompt parameter, "${slug}", has no options to select from.`);
This function isn't directly related to prompts.

```suggestion
    throw new Error(`The required parameter, "${slug}", has no options to select from.`);
```

2022-11-23 18:21 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +    throw new Error(`The required prompt parameter, "${slug}", has no options to select from.`);
Hmm, does this match our API semantics? I would almost assume if a user passes an empty array of options, we would ignore it.

2022-11-23 18:21 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +      typeof option === "object" && "value" in option ? option.value : option
I'd add a helper for this:

```
const isOptionObject = <TOption>(
  opt: TOption | SelectOption<TOption>
): opt is SelectOption<TOption> => {
  return typeof opt === "object" && opt != null && "value" in opt;
};
```

FYI I noticed `label` is required in `SelectOption` but should be optional. Can you fix?

2022-11-23 18:21 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +      return option.toISOString();
Same here as above -- let's continue to use `toISOString(option)` so we retain the time zone when serialized for dates.

2022-11-23 18:21 UTC, colinking commented on packages/airplane/internal/prompt/index.ts
> +export const prompt = async <TParams extends PromptInputParams = Record<string, never>>(
You'll want to remove this `Record<string, never>` default as it breaks intellisense:

before:
<img width="840" alt="CleanShot 2022-11-23 at 13 15 28" src="https://user-images.githubusercontent.com/2907397/203619589-be610aac-f6ed-49bd-bcfe-165c98e944d7.png">

after:

<img width="882" alt="CleanShot 2022-11-23 at 13 15 47" src="https://user-images.githubusercontent.com/2907397/203619594-5f3ad561-443d-4c05-8a36-54a75e909903.png">

2022-11-23 18:21 UTC, colinking commented on packages/airplane/internal/prompt/index.ts
>  export const datetime = async (
Doing so should fix https://linear.app/airplane/issue/TSK-465/prompt-output-should-be-undefined-when-optional for these methods

2022-11-23 18:21 UTC, colinking commented on packages/airplane/internal/prompt/index.ts
> +export const prompt = async <TParams extends PromptInputParams = Record<string, never>>(
Seems like you can just do:

```
export const prompt = async <TParams extends PromptInputParams = Record<string, never>>(
  params: TParams,
  opts: BasePromptOptions = {}
): Promise<Resolve<InputToOutputParamValues<TParams>>> => {
  // ...
};
prompt.confirm = confirm;
prompt.integer = integer;
// ...
```

2022-11-23 18:23 UTC, colinking requested changes
LGTM, apart from some minor comments below. Is the plan to keep the old methods, or do we want to deprecate them? What's the plan around adding the alternative array notation?

2022-11-28 18:31 UTC, colinking commented
@ericliuche one more ask -- can you add JSDoc comments to the prompt methods, similar to what I did in this PR? https://github.com/airplanedev/js-sdk/pull/208

2022-11-28 20:23 UTC, ericliuche commented on packages/airplane/internal/params/params_serialized.ts
> +        name: param.name ? param.name : slug,
i'll add a task to do this in a later change, we already do it for the python sdk
`name=param_config.name or inflection.humanize(default_slug),`

2022-11-28 20:41 UTC, ericliuche commented on packages/airplane/internal/params/params_serialized.ts
> +    throw new Error(`The required prompt parameter, "${slug}", has no options to select from.`);
yup you're right. should we add the check to parameter verification?

<img width="484" alt="Screen Shot 2022-11-28 at 3 40 56 PM" src="https://user-images.githubusercontent.com/11494140/204376548-b248f6d3-3264-4d33-a7d4-7661fb7d744c.png">

2022-11-28 20:43 UTC, ericliuche commented on packages/airplane/internal/prompt/index.ts
>  export const datetime = async (
hmm would that require us having to write a template that converts `PromptOptions` to `InputParams`?

2022-11-28 20:44 UTC, ericliuche commented
`Is the plan to keep the old methods, or do we want to deprecate them?`
i think we should deprecate the old methods, should i just mark them as deprecated here?

`What's the plan around adding the alternative array notation?`
we can do that in a follow up change, i'll add a task for it

2022-11-28 23:04 UTC, colinking commented
> i think we should deprecate the old methods, should i just mark them as deprecated here?

Sweet, use this annotation for that and VSCode will mark usage with a strikethrough: https://jsdoc.app/tags-deprecated.html

2022-11-28 23:07 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +    throw new Error(`The required prompt parameter, "${slug}", has no options to select from.`);
We apparently do this in our UI:

<img width="784" alt="CleanShot 2022-11-28 at 18 05 42" src="https://user-images.githubusercontent.com/2907397/204399442-f0583f58-8aaf-4126-983b-bbe340ee675d.png">

Returning an error from the API SGTM. Can you add a Linear for that?

2022-11-29 15:21 UTC, ericliuche commented on packages/airplane/internal/params/params_serialized.ts
> +    throw new Error(`The required prompt parameter, "${slug}", has no options to select from.`);
https://linear.app/airplane/issue/TSK-1193/add-parameter-verification-check-that-empty-options-is-not-allowed

2022-11-29 16:56 UTC, ericliuche commented
`JSDoc comments to the prompt methods` 

@colinking i just added docs to the new `prompt` method I added since the other methods are deprecated now. is that fine?

2022-11-29 18:44 UTC, colinking approved these changes

2022-11-29 18:44 UTC, colinking commented on packages/airplane/internal/prompt/index.ts
> + * @deprecated since v0.2.23, use `prompt()` instead
This method's actually a convenience method (given an arbitrary list of elements, you can create a select parameter from it), so there's actually no direct replacement with `prompt`. Is there a way we can keep it or something similar around?

2022-11-29 18:44 UTC, colinking commented on packages/airplane/internal/prompt/prompt.test-d.ts
> +    const _myPrompt = prompt({});
add twoslash check

2022-11-29 18:44 UTC, colinking commented on packages/airplane/internal/params/params_serialized.test.ts
> +        regex: "$.*^",
```suggestion
        regex: "^.*$",
```

2022-11-29 19:30 UTC, ericliuche commented on packages/airplane/internal/prompt/index.ts
> + * @deprecated since v0.2.23, use `prompt()` instead
ah good point, will just remove the deprecated tag for now

2022-11-29 21:44 UTC, merged