Add sleep SDK
airplanedev/js-sdk pull request #241
Opened 2022-12-15 23:15 UTC by kellymtrinh

Opening for feedback- this is pending the discussion we had about naming. (Timers = api for timers, which we originally were going to have. The SDK/usage refers to everything as sleep.)

Usage examples:
`await airplane.sleep("5s")` - we type the duration input to be "123unit" or "123 unit". 
Valid units are:
`"d" | "hr" | "h" | "min" | "m" | "sec" | "s" | "ms".` I could have added more but I thought these were a good starting point/subset of popular formats that we could document.

- I'm using the `vercel/ms` library since it seems lightweight and is what temporal uses. Note that the latest version is called canary even though it's[ been out for over a year (it's the only one that has TS support](https://github.com/vercel/ms/issues/184)). 
- 
# Test Plan
- [x] Deployed a workflow locally  that uses sleep and verified in the temporal UI that a timer started with the correct duration. Checked the run_timers table for correct dates. Verified with print statements that it waited until the end to continue when I awaited the airplane.sleep().
- [x] Deployed a standard task locally that uses sleep and verified it waited the specified number of seconds until continuing. (This is implemented with setTimeout)

2022-12-19 20:27 UTC, colinking requested changes

2022-12-19 20:27 UTC, colinking commented on packages/workflow-runtime/internal/activities.ts
> +      const activityStartTime = Context.current().info.scheduledTimestampMs;
Hmm, it's not clear from their docs if this is when the _current_ activity task was scheduled or when the _first_ activity task was scheduled. Can you check with the Temporal folks?

IOW, is it the first or second "ActivityTaskScheduled" in this diagram: https://docs.temporal.io/concepts/what-is-a-schedule-to-start-timeout

Ideally, we use the first!

2022-12-20 21:38 UTC, kellymtrinh commented on packages/workflow-runtime/internal/activities.ts
> +      const activityStartTime = Context.current().info.scheduledTimestampMs;
I'll check with them- 🤔 the JS docs suggest it's the "current" activity everywhere [though](https://github.com/temporalio/sdk-typescript/blob/main/packages/activity/src/index.ts#L113-L153)

2022-12-21 01:16 UTC, kellymtrinh commented
(Pending clarification from temporal about activity scheduled time- I'm going to test out logging activity scheduled times for a few activities in the same workflow and see if they're different though. )

2022-12-21 22:24 UTC, colinking approved these changes

2022-12-21 22:24 UTC, colinking commented on packages/airplane/internal/runtime/index.ts
> +  ms: number;
Do we still use `str`? Can we just pass through `ms` instead? IOW, `runtime.sleep(ms: number)`

2022-12-21 22:24 UTC, colinking commented on packages/airplane/internal/sleep/index.ts
> +  if (!durationMs) {
From what I can tell, `ms` will throw errors if the duration is invalid. I skimmed the code and see that it returns `NaN` in some cases and can return `0`. Is that what you are handling here? If so, the error message could be better.

2022-12-21 22:24 UTC, colinking commented on packages/airplane/internal/sleep/index.ts
> +    throw new Error("sleep duration is required");
This error message seems to make more sense up here?

```suggestion
    throw new Error("expected a duration for how long to sleep (e.g. '1h' to sleep for an hour)");
```

2022-12-21 22:24 UTC, colinking commented on packages/workflow-runtime/internal/activities.ts
> +      // Use the time the activity was scheduled as the timer start time
Let's dump some context as a comment here. Thanks for checking w/ them in Slack!

```suggestion
      // Compute when the sleep should end based on the timestamp of when this activity
      // was originally scheduled (IOW, if Temporal performs multiple attempts at executing this
      // activity, this timestamp will always be the same).
```

2022-12-21 22:24 UTC, colinking commented on packages/airplane/internal/sleep/index.ts
> +export const sleep = async (duration: StringValue) => {
Add JSDoc. Also indicate that this method is in beta and may change. See prompts for JSDocs examples.

2022-12-22 19:55 UTC, kellymtrinh commented on packages/workflow-runtime/internal/activities.ts
> +      const activityStartTime = Context.current().info.scheduledTimestampMs;
![Screenshot 2022-12-21 at 11 53 29 AM](https://user-images.githubusercontent.com/8205327/209215707-e3e37efc-739e-4566-9a11-a3678b157b9d.png)

2022-12-22 21:55 UTC, merged