Add convertToDef function on airplane.task and airplane.workflow
airplanedev/js-sdk pull request #338
Opened 2023-03-28 23:06 UTC by ameyakhare

Adds a function to the task object to convert its config to a task definition that lib understands.

2023-03-29 22:55 UTC, ericliuche commented on packages/airplane/internal/config.ts
> +      parameters: config.parameters
use `SerializeParams`

2023-03-29 22:55 UTC, ericliuche commented on packages/airplane/internal/config.ts
> +    sql: {
move up a level, outside `sql`

2023-03-29 22:55 UTC, ericliuche commented on packages/airplane/internal/config.ts
> +const convertToDef = <TParams extends InputParams>(
merge the logic in `normalizeConfig` here

2023-03-29 23:26 UTC, ameyakhare commented on packages/airplane/internal/config.ts
> +export type SQLTaskConfig<TParams extends InputParams> = TaskConfig<TParams> &
@colinking eyes here for bindings and configs for sql tasks

2023-03-29 23:26 UTC, ameyakhare commented on packages/airplane/internal/config.ts
> +              resource: sqlConfig.resource,
@colinking typecasted const var access since the config object passed in could be a TaskConfig or SQLTaskConfig

2023-04-05 19:43 UTC, colinking reviewed
First pass.

2023-04-05 19:43 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +      name: param.name ? param.name : humanizeString(slug),
We already do this in `normalizeConfig`. Why do it here, too?

2023-04-05 19:43 UTC, colinking commented on packages/airplane/internal/config.ts
> + * Builtin task bindings are currently in beta.
```suggestion
 * Declaring SQL tasks with JavaScript is currently in beta.
```

Unrelated, but this made me notice `Airplane Views are currently in beta.` is outdated -- can you remove that?

2023-04-05 19:43 UTC, colinking commented on packages/airplane/internal/config.ts
> +    transactionMode?: TransactionMode;
Add documentation (with examples and docs links) for these fields. See the types above for examples, e.g. `TaskConfig`.

2023-04-05 19:43 UTC, colinking commented on packages/airplane/internal/config.test.ts
> +    expect(def.node.entrypoint).toEqual("foo");
This should not be set.

2023-04-05 19:43 UTC, colinking commented on packages/airplane/internal/config.test.ts
> +  test("config serialized to definition", () => {
Nice. Add a view and SQL test, too.

2023-04-05 19:43 UTC, colinking commented on packages/airplane/internal/config.ts
> +task.sql = sqlTask;
Add type tests for `airplane.task.sql` in `config.test-d.ts`. This ensures that we're producing readable (and correct) types. These tests are checked via `eslint-plugin-expect-type`. `eslint` will automatically fix any of the `// ^?` comments to include the corresponding type.

2023-04-05 19:44 UTC, colinking commented on packages/airplane/internal/config.test.ts
> +    expect(def.node.entrypoint).toEqual("foo");
Ah, I see this is a parameter. Nevermind.

2023-04-05 19:59 UTC, colinking requested changes
Generally looks good. I just want to approve the type test changes.

If you haven't already, let's give this a good test in studio/builds before we start using this `convertToDef` method.

2023-04-05 19:59 UTC, colinking commented on packages/airplane/internal/config.ts
> +export const serializedParamToDefParam = (param: SerializedParam): ParamDef => {
unexport

2023-04-05 19:59 UTC, colinking commented on packages/airplane/internal/config.ts
> +  Omit<TaskConfig<TParams>, "resources" | "runtime"> & {
We don't support `envVars` for SQL tasks, either.

2023-04-05 19:59 UTC, colinking commented on packages/airplane/internal/config.ts
> +export type SQLTaskConfig<TParams extends InputParams> = TaskConfig<TParams> &
This is bringing back the omitted fields, e.g. `resources`:

<img width="839" alt="CleanShot 2023-04-05 at 15 50 32" src="https://user-images.githubusercontent.com/2907397/230190967-2bfb52ea-642a-4b1f-885c-62d8c19f4292.png">

```suggestion
export type SQLTaskConfig<TParams extends InputParams> =
```

2023-04-05 19:59 UTC, colinking commented on packages/airplane/internal/config.ts
> +    return run as Run<
This should be `BuiltInRun` (which does not have a `taskID` field). You'll also need to add a `WrappedBuiltInRunFunc` so that this task returns a `BuiltInRun`.

2023-04-05 19:59 UTC, colinking commented on packages/airplane/internal/config.ts
> +type TaskDef<TParams extends InputParams> = {
Do you need this type? IIUC, this is only used in one place (`convertToDef`).

2023-04-05 19:59 UTC, colinking commented on packages/airplane/internal/config.ts
> +const convertToDef = <TParams extends InputParams>(
+1. Can you just call `normalizeConfig` from `convertToDef` instead of duplicating the dedent/humanize logic?

2023-05-18 16:09 UTC, colinking commented on packages/airplane/internal/config.ts
> +    convertToDef: convertToDef(config, "node"),
It seems confusing to have both `config` and `convertToDef`. It looks like Views only uses `config.slug`. Discovery is presumably the only other place looking at `config` which would get migrated to `convertToDef`?

2023-05-18 16:09 UTC, colinking commented on packages/airplane/internal/config.ts
> +const convertToDef = <TParams extends InputParams>(
Does this need to be a function? What if it was `__airplane.def` but without `node.entrypoint` or `entrypointFunc` set, and it was up to discovery to set those fields? That would allow Views to switch from `config.slug` to `def.slug` without having to call this function with fake values just to get the slug.

2023-05-18 16:09 UTC, colinking commented on packages/airplane/internal/config.ts
> +    convertToDef: convertToDef(config, "node"),
Could we remove `config` in this PR? That way we only have one of these. This is assuming we update Views and discovery first with logic for using `convertToDef` if set, else `config`.

2023-05-18 16:09 UTC, colinking commented on packages/airplane/internal/config.ts
> +      timeout: config.timeout,
Maybe just spread out config with `...config`? Same idea as how it works for `__airplane.config` above. That way we don't need to add new task fields here unless their JS format differs from their definition format.

You can do the same for the type, ala `type TaskDef<TParams extends InputParams> = Omit<TaskConfig<TParams>, "parameters"> & { parameters: ParamDef[] }`

2023-05-18 16:11 UTC, colinking commented on packages/airplane/internal/config.ts
> +  schedules?: Record<string, Schedule<InputParamValues<TParams>>>;
You'll need to serialize schedule parameter values, too. See how `serializeParams` calls `serializeParamValue` on `default`.

2023-05-18 16:21 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +export const serializeParamDef = (
Ah, nm. The goal of `params_serialized.ts` is to represent the API format for parameters. However, I suppose there's a separate _definition_ format.

2023-05-18 16:21 UTC, colinking commented on packages/airplane/internal/params/params_serialized.ts
> +export const serializeParamDef = (
Let's keep the definition format out of this file, then, since it's unrelated to the serialized API format. How about we just inline this in `serializedParamToDefParam`?

2023-05-18 16:22 UTC, colinking commented on packages/airplane/internal/config.ts
> +type ParamDef = {
To align with the other parameter types, do `DefParam` (e.g. InputParam/SerializedParam/...)

2023-05-18 16:23 UTC, colinking commented on packages/airplane/internal/config.ts
> +const serializedParamToDefParam = (param: SerializedParam): ParamDef => {
nm see comment above

2023-06-30 19:31 UTC, closed without merging